spring.application.name=job_applications_tracker
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/job_applications_tracker
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true